Fix/register: 추방 모드 구현
project-matching/project-matching-frontend pull request #76
Opened 2022-09-22 05:42 UTC by younchong

* 추방 버튼 활성화
* 추방 api 연결

todos
* side component 렌더링하기 (update이후에, 처음 정보도 자체에서 받아오기)

2022-09-22 07:28 UTC, Olivia-SY129 requested changes
리뷰 확인하시고 코멘트 혹은 다시 pr 날려주시면 확인하겠습니다. 수고하셨습니다.

2022-09-22 07:28 UTC, Olivia-SY129 commented on src/components/Post/Side.tsx
> +              console.log(applicant.projectParticipateNo);
콘솔 제거해주세요.

2022-09-22 07:28 UTC, Olivia-SY129 commented on src/components/Post/Side.tsx
> +    // rejectModal에서 상황ㅇ에 맞게 나누면 됨
오타있습니다!

2022-09-22 07:28 UTC, Olivia-SY129 commented on src/components/Modals/RejectModal.tsx
> +    await ProjectService.rejectProjectApplicant(participateNo, { reason }) :
거절과 추방을 위해 한 모달을 사용하신다면 아래 '거절 사유' 나 '거절하기' text 값도 동적으로 수정해주세요.
또한 해당 모달은 확인/취소 버튼으로 구현된 모달이므로 파일 이름도 이에 맞게 수정해주시면 좋을 것 같습니다.

2022-09-22 14:54 UTC, younchong commented on src/components/Modals/RejectModal.tsx
> +    await ProjectService.rejectProjectApplicant(participateNo, { reason }) :
아래 '거절 사유' 나 '거절하기' text 값도 동적으로 수정해주세요.
 파일 이름도 이에 맞게 수정해주시면 좋을 것 같습니다.
이 부분 좀 더 자세히 설명해 주실 수 있나요?

2022-09-23 01:10 UTC, Olivia-SY129 commented on src/components/Modals/RejectModal.tsx
> +    await ProjectService.rejectProjectApplicant(participateNo, { reason }) :
추방 모달로 사용하실 거라면 모달 버튼 text값을 그에 맞게 동적으로 바꾸는게 좋을 것 같습니다. 추방 모달로 사용할 때 props 값을 추가로 받으니  그 값을 사용하시면 될 것 같습니다.

2022-09-26 05:59 UTC, younchong commented on src/components/Modals/RejectModal.tsx
> +    await ProjectService.rejectProjectApplicant(participateNo, { reason }) :
확인하고 변경했습니다!

2022-09-26 06:08 UTC, merged